### ISSUE TITLE
Pass data between apps

### ISSUE THREAD

**Issue by lachlandeer** [lachlandeer/otree-info-social-norms#1]
we need the data from `GroupPreferenceElicitation` to be available in the `asset_live_game`

I've tried to throw the data to the participants table during the `GroupPreferenceElicitation` app, but whenever i try and access it either

* on the next page of the  `GroupPreferenceElicitation` app  or
* In the `asset_live_game` app

via the participants table an attribute error is thrown

**Comment by jasonyji** [comment]
Which line of code does this error occur?

I tried specifying `player.participant.vars['Individualism']` from the `GroupPreferenceElicitation` app within the `asset_live_game` app, and the value could be retrieved successfully.

**Comment by lachlandeer** [comment]
OK great 

I see that if we try and get it in the function `vars_for_template()` it works.

Can you use this information (individualist vs collectivist) to the table of signals assigned to players. See #9

**Comment by lachlandeer** [comment]
closing as this seems to actually work. 

re-open if we find issues down the line
