### ISSUE TITLE
Move Radio button in GroupPreference Elicitation

### ISSUE THREAD

**Issue by lachlandeer** [lachlandeer/otree-info-social-norms#10]
The screen currently looks like this:
![image](https://github.com/lachlandeer/otree-info-social-norms/assets/4036802/44ae1df7-9a99-428c-9e1c-9f40f50371b9)

Can we move the Statement A radio button from the bottom of the screen to be next to (on the left of) the **bold faced** Statement A. The same for Statement B.

**Comment by jasonyji** [comment]
Solved. Please take a look at the pull request...
