### ISSUE TITLE
Instructions for all apps

### ISSUE THREAD

**Issue by lachlandeer** [lachlandeer/otree-info-social-norms#2]
Need to integrate instructions from our shared dropbox folder into each app

**Comment by lachlandeer** [comment]
Hi @jasonyji 

As your next task, could you add instructions into the apps.

They are in our Dropbox folder, the most recent one is `Instructions/Instructions_202406_seed.docx`. Perhaps drop an email to Yi-shan and see if there is an update (though I doubt it)

If you don't have dropbox access, let us know and we can add you

Thanks in advance for you assistance!

Cheers
lachlan

**Comment by jasonyji** [comment]
Hi @lachlandeer 

I have finished most of the programming work. Please check and let me know if anything is unclear.

Best, Yi
