### ISSUE TITLE
General Beautifying

### ISSUE THREAD

**Issue by lachlandeer** [lachlandeer/otree-info-social-norms#4]
Apps need beautifying according to YSL preferences. 

Discuss what is needed, document here, then implement

**Comment by lachlandeer** [comment]
In the app `asset_live_game`:

- YSL wants the names of players to not be in a "strange order" i.e. order should be Player 1, Player 2, Player 3 in the table, but we also need players to be randomly assigned to columns/signals

**Comment by lachlandeer** [comment]
In the `GroupPreferenceElicitation` game 

- YSL wants the radio buttons to appear next the **bold** text for each statment, rather than at the bottom of the page

**Comment by jasonyji** [comment]
> In the app `asset_live_game`:
> 
> * YSL wants the names of players to not be in a "strange order" i.e. order should be Player 1, Player 2, Player 3 in the table, but we also need players to be randomly assigned to columns/signals

Solved.

**Comment by jasonyji** [comment]
> In the `GroupPreferenceElicitation` game
> 
> * YSL wants the radio buttons to appear next the **bold** text for each statment, rather than at the bottom of the page

Solved
