### ISSUE TITLE
All collectivism survey questions + Random ordering

### ISSUE THREAD

**Issue by lachlandeer** [lachlandeer/otree-info-social-norms#5]
At present we only have the first 8 questions from our collectivism survey

we need to:

- [ ] Have all questions included
- [ ] Randomize the order the questions appear (Unique to the player as far as i am aware -- ask YSL)
- [ ] Keep a max of 8 questions appearing per page

**Comment by lachlandeer** [comment]
Hi @jasonyji 

Any progress here?

**Comment by jasonyji** [comment]
Almost there. I was a bit busy last week. I will check the details again by this weekend.

**Comment by jasonyji** [comment]
solved
