### ISSUE TITLE
Adding Collectivist vs Individualist Info to the live game

### ISSUE THREAD

**Issue by lachlandeer** [lachlandeer/otree-info-social-norms#9]
Following how the instructions appear on dropbox, we need to have the collectivist or individualist information available for subjects in the "Guess the target value" stage of the `asset_live_game` app.

Once #1 is fixed, this should be doable. 

Note that this is only for treatments where that info (C or I) is available.

**Comment by lachlandeer** [comment]
We want to update the table that displays signals and players in the `asset_live_game` to look like as follows (borrowed from the instructions)

![image](https://github.com/lachlandeer/otree-info-social-norms/assets/4036802/49adbcdb-df10-4b7f-9c6c-426e90cec61c)


so that individualists are labelled as such with the "one person" icon, and collectivists with the three person icon.

These icons are stored in `_static/data` as `person.png` and `people.png`

Once that is implemented, we want to be able to turn on/off whether this information is available by treatment. For now think of two treatments:

(i) the icons are visible
(ii) the icons are not visible

**Comment by jasonyji** [comment]
Solved. Please take a look at the pull request...
